### ISSUE TITLE
Failed to connect: Premature end of file

### ISSUE THREAD

**Issue by jean-christophe-manciot** [cisco-ie/anx#1]
- Ubuntu 17.10
- anx commit: cccc6fc9236f8b5bd53940b784d4c50934cc5333
- Target: CSR 1000v 16.6.1
- Build as non-root with ```$ docker-compose up -d```.

![failed-to-connect](https://user-images.githubusercontent.com/13176858/38631124-252cf7ee-3db9-11e8-97b8-b10c46b27014.png)

The whole build & run log is [here](https://github.com/cisco-ie/anx/files/1899689/failed-to-connect.log.txt)
.
At the same time, I am **able to manually list all the supported Yang module**s with:
```
ssh -p 830 admin@172.21.85.131 -s netconf
admin@172.21.85.131's password: 
<?xml version="1.0" encoding="UTF-8"?>
<hello xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
<capabilities>
<capability>urn:ietf:params:netconf:base:1.0</capability>
<capability>urn:ietf:params:netconf:base:1.1</capability>
<capability>urn:ietf:params:netconf:capability:writable-running:1.0</capability>
<capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
<capability>urn:ietf:params:netconf:capability:validate:1.0</capability>
<capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
<capability>urn:ietf:params:netconf:capability:rollback-on-error:1.0</capability>
<capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
<capability>urn:ietf:params:netconf:capability:interleave:1.0</capability>
<capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all-tagged</capability>
<capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2016-06-21&amp;module-set-id=2e15cdf8fe537391000954ba924472e3</capability>
<capability>http://tail-f.com/ns/netconf/actions/1.0</capability>
<capability>http://tail-f.com/ns/netconf/extensions</capability>
<capability>http://cisco.com/ns/cisco-xe-ietf-ip-deviation?module=cisco-xe-ietf-ip-deviation&amp;revision=2016-08-10</capability>
...
```

**Comment by sbyx** [comment]
Could you please try appending the port with :830, i.e. "172.21.85.131:830" as NETCONF device (without "). If it solves the issue for you, I will add a bit of logic to detect whether the device actually uses 830 or 22.

**Comment by jean-christophe-manciot** [comment]
It does solve the issue.
I would recommend to test 830 first since 22 is the old agent on IOS-XE: cf. @iipspace [article](http://blog.ipspace.net/2017/04/netconf-agents-on-cisco-ios-xe-16x.html).

**Comment by sbyx** [comment]
Thanks, fixed: https://github.com/cisco-ie/anx/commit/8428bd52e0b7b59e9861b1ccd4c510451d25f71f

**Comment by jean-christophe-manciot** [comment]
@sbyx 
I have rebuilt the container with latest commit d8757fc8f82a669f2702f5bc51926bace34d72e1
Unfortunately, the issue is **still there**: we have to enter the port number otherwise the same ```Premature end of file``` error message shows up.

**Comment by sbyx** [comment]
I just verified it again with a CSR1000v on VIRL that has netconf-yang configured.
For me it works without giving a port, not sure how our setup differs.

**Comment by jean-christophe-manciot** [comment]
Maybe the CSR1000v release number.
Or its configuration (in particular, ```netconf ssh``` is **not enabled**):
```
netconf-yang cisco-odm actions OSPF
netconf-yang cisco-odm actions IPRoute
netconf-yang cisco-odm actions Diffserv
netconf-yang cisco-odm actions BFDNeighbors
netconf-yang cisco-odm actions BridgeDomain
netconf-yang cisco-odm actions VirtualService
netconf-yang cisco-odm actions EthernetCFMStats
netconf-yang cisco-odm actions MPLSLDPNeighbors
netconf-yang cisco-odm actions MPLSStaticBinding
netconf-yang cisco-odm actions MPLSForwardingTable
netconf-yang
!
restconf
!
ip ssh time-out 10
ip ssh rsa keypair-name XEv_Spine_31_rsakey
ip ssh version 2
ip ssh dh min size 4096
ip ssh stricthostkeycheck
ip ssh pubkey-chain
  username admin
   key-hash ssh-rsa 12E96F16DAD2F5B51942C26F3ED164DD root@SAMSUNG-Ubuntu
ip ssh server algorithm encryption aes128-ctr aes192-ctr aes256-ctr
ip ssh client algorithm encryption aes128-ctr aes192-ctr aes256-ctr
ip scp server enable
```
