### ISSUE TITLE
why "generate metric.json" dissappeared

### ISSUE THREAD

**Issue by shaitmm** [cisco-ie/anx#16]
im using the version from https://github.com/cisco-ie/anx

**Comment by shaitmm** [comment]
![image](https://user-images.githubusercontent.com/6395735/68280152-ed602780-00af-11ea-8530-88441ad8e492.png)

**Comment by shaitmm** [comment]
![image](https://user-images.githubusercontent.com/6395735/68280368-5e074400-00b0-11ea-9c64-68812a217244.png)
why i cannt see the "generate metric.json" button

**Comment by sbyx** [comment]
This feature has never been part of this repository. I would suggest using Telegraf as collector: https://github.com/influxdata/telegraf

**Comment by HackedBaked** [comment]
@sby sorry to open this again, It is not clear to me what telegraf has to do with adding that button to the web interface. Was there a fork for this repo somewhere that has access to that button? Can you be more specific why you suggest using "Telegraf as collector"?
