### ISSUE TITLE
Add option for custom NETCONF port at login

### ISSUE THREAD

**Issue by nickrusso42518** [cisco-ie/anx#17]
It would be excellent if a TCP port text box was present on the login page, pre-populated to 830. The DevNet sandboxes, for example, use port 10000, and being able to use this tool with those always-on resources would be very helpful.

**Comment by sbyx** [comment]
You can already do that by appending a : followed by the portnumber to the hostname / IP in the NETCONF device field.

But granted it is not documented ;)
________________________________

**Comment by nickrusso42518** [comment]
OK, I see two easily alternatives.

1. Put a small note above the textbox on the logic page saying so.
2. Make a note in the README saying so, and providing a simple example.

**Comment by sbyx** [comment]
Added a hint on the login form.
