### ISSUE TITLE
Ability to edit sensor-path before subscribing through GNMI

### ISSUE THREAD

**Issue by jc-rode** [cisco-ie/anx#18]
Currently we have to subscribe all nodes without the ability to filter by specifying some keys.

For instance, if there is some data under an address-family key, we will get data for all address-families but it would be nice to be able to edit the sensor-path to only subscribe to one address-family by specifying the key.  That would reduce the amount of data being streamed and allow us to test the more specific sensor-path before configuring it on the device for dialout.

**Comment by sbyx** [comment]
Done

**Comment by jc-rode** [comment]
So quick... awesome ! Many thanks !
