### ISSUE TITLE
Why "generate metrics.json" was removed from new version?

### ISSUE THREAD

**Issue by yongpro** [cisco-ie/anx#22]
After checked the new version, I found the "generate metrics.json" function that was removed... why to remove the function... that is easy to create metric and deploy in piepline when export the telemetry to influxDB...

Thanks
Frank

**Comment by HackedBaked** [comment]
Why was this closed? I am curious to why it was removed as well. Was it put somewhere else? Where can I find "generate metrics.json" now on the latest version?
