### ISSUE TITLE
Cisco NCS5500 expects RPC

### ISSUE THREAD

**Issue by tylersiemers** [cisco-ie/anx#3]
Does the NCS 5500 platform not accept YDK from anx netconf-console? I can do get calls but trying to do edit-config merge I get the following error:

> RP/0/RP0/CPU0:Apr 20 20:56:35.216 : netconf[1104]: ERR: NC: Error, expected <rpc> element, instead <close-session> was received
> RP/0/RP0/CPU0:Apr 20 20:56:35.216 : netconf[1104]: ERR: NC: No message-id in YFW response

**Comment by sbyx** [comment]
Not sure what you are trying to do with YDK.

The Netconf console expects netconf XML messages such as the ones you can prepare with the get-config or edit-config buttons beside the input text box.
